### ISSUE TITLE
Configuring a direct source with delete behaviour causes a "hi" to be printed to the console

### ISSUE THREAD

**Issue by Neurrone** [synthizer/synthizer-rs#2]
I know this sounds strange, but doing `src.config_delete_behavior(&del_cfg).unwrap();` causes a "hi" to be printed to the console.

I'm using the code verbatim in https://github.com/synthizer/synthizer-rs/blob/master/synthizer/examples/linger.rs to play a sound with linger (something like a footstep) and noticed this. Below is the code that I'm using.

```
pub fn play_with_linger(&self, buffer: &syz::Buffer) {
        let del_cfg = syz::DeleteBehaviorConfigBuilder::new()
            .linger(true)
            .linger_timeout(10.0)
            .build();
        let src = syz::DirectSource::new(&self.context).unwrap();
        let generator = syz::BufferGenerator::new(&self.context).unwrap();
        generator.set_buffer(buffer).unwrap();
        src.add_generator(&generator).unwrap();
        src.config_delete_behavior(&del_cfg).unwrap(); // this line
        generator.config_delete_behavior(&del_cfg).unwrap();
        src.play().unwrap();
    }
```

**Comment by Neurrone** [comment]
Forgot to mention, I'm on version 0.3.3 of the Synthizer crate.

**Comment by ahicks92** [comment]
Bleh ok.  There was a debug print that landed in mainline Synthizer.  I didn't realize that hit actual releases.

I'll fix that this morning and roll releases across the board.

**Comment by Neurrone** [comment]
Thanks!

While we're on the subject of linger, I really like this convenience feature because its the one thing that exists outside the model of have the soundsystem observe the world and it updates itself based on the world state similar to React's reconciliation.

There were instances where I just needed a sound to be played and didn't want to have to manage the lifetime of its objects.

**Comment by ahicks92** [comment]
Ok, this is fixed.  I've been awake for all of 20 minutes so if it's still there we'll do this again when I'm actually alert.

I like lingering from the external user perspective--even with what little we have now it goes beyond everything I know of.  That said it may be slightly buggy still, so if you find issues do open something against the main synthizer repo.  I hate how I can either write the library or use the library due to lack of time to do both but that's life I suppose.
