### ISSUE TITLE
Derive more traits

### ISSUE THREAD

**Issue by Neurrone** [synthizer/synthizer-rs#3]
I wanted to store sources in a hash map or other data structure, and do comparisons to check for equality.

The use case is updating the audio simulation by observing game state, which requires some bookkeeping of sources etc.

Currently, I believe the only trait that is derived is clone. Could more traits be derived / implemented where it makes sense?

**Comment by ahicks92** [comment]
Yes, I thought I already did in fact.

You can depend on this repo instead of the crates.io version.  Releases take 20 minutes or so so I'm not eager to keep doing them for small things like this. I can get you the traits in the next 5 minutes or so, I think, at least as far as getting objects to hash/compare to themselves.  If you want to get the objects hash/comparing to raw handles etc, feel free to do a PR: inter-type conversions requires a lot of manual code.

**Comment by ahicks92** [comment]
Open another issue if I missed one.  Note that `StreamHandle` can't be `Clone`.

On the whole I say "submit a PR if you want it" for inter-object-type comparisons but find that really I'm not sure I'm super thrilled by inter-object comparisons.  If that's something you really need, let's track it separately; I would want to know what the use case the casting support doesn't cover.

Ordering is not stable from one program run to the next, but I think that goes without saying.
