### ISSUE TITLE
Checking if audio is paused/playing?

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [synthizer/synthizer-rs#4]
Hello
I searched the struct methods and didn't find something that tells me if a source/generator are paused, I need this for something, Is this not added yet/not planned to be added, Or did I mis it somewhere?

**Comment by ahicks92** [comment]
It's not added to Synthizer itself on purpose.  Like with reading properties, it is not possible to do this accurately and efficiently, because the underlying architecture has a bunch of queues.  You need to track that yourself with an additional boolean somewhere.

Do not use Synthizer to store state.  It will not work out for you in any way whatsoever.
